name: C++ Build and Run

on:
  push:
    branches: [main, hw]
  pull_request:
    branches: [main, hw]

jobs:
  build-docker:
    uses: ./.github/workflows/docker-build.yml

  test:
    name: Build and Test
    needs: build-docker
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Docker image
        uses: actions/download-artifact@v4
        with:
          name: cpp_course-image

      - name: Load Docker image
        run: docker load -i cpp_course_image.tar

      - name: Run tests in container
        run: |
          # Create results directory on host
          mkdir -p test-results
          
          # Mount repository and results directory
          docker run --name cpp_course_container \
            -v ${{ github.workspace }}:/workspace \
            bmstu_cpp_course-bmstu:latest \
            bash -c "cd /workspace && \
                    mkdir -p build && \
                    cd build && \
                    cmake .. -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_CXX_FLAGS='-fprofile-arcs -ftest-coverage' && \
                    cmake --build . && \
                    cd .. && \
                    bash docker/run_tasks/run.sh && \
                    find build -name '*.xml' -type f -exec cp {} /workspace/test-results/ \;"
          
          # Show what test results were found
          echo "Found test results:"
          ls -la test-results/ || echo "No test results directory found"

      - name: Upload test results
        if: always()
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          name: test_results_xml
          path: test-results/
          if-no-files-found: warn
          retention-days: 5
